name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runtime: [win-x64] #, linux-x64, osx-x64]
    runs-on: windows-latest
    env:
      SRC: 'DlMirrorSync'
      NAME: 'DlMirrorSync'
      FRAMEWORK: 'net8.0'
      VERSION: '0.2.0'
      OUTPUT_ROOT: './publish'
    steps:
    - uses: actions/checkout@v3
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish ./${{ env.SRC }}/${{ env.NAME }}.csproj -c Release -r ${{ matrix.RUNTIME }} --framework ${{ env.FRAMEWORK }} --self-contained true /p:Version=${{ env.VERSION }} /p:PublishReadyToRun=true /p:PublishSingleFile=True /p:PublishTrimmed=false /p:IncludeNativeLibrariesForSelfExtract=True /p:PublishDir="bin\Release/${{ env.FRAMEWORK }}/${{ env.RUNTIME }}" --output ${{ env.OUTPUT_ROOT }}/standalone/${{ matrix.RUNTIME }}
    - name: Setup WiX
      run: dotnet tool install -g wix; wix extension add -g WixToolset.UI.wixext
    - name: Build installer
      working-directory: ./MsiInstaller
      run: dotnet build MsiInstaller.wixproj -c Release -r win-x64 --output ${{ env.OUTPUT_ROOT }}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.NAME }}-${{ env.VERSION }}-standalone-${{ matrix.RUNTIME }}
        path: ${{ env.OUTPUT_ROOT }}/standalone/${{ matrix.RUNTIME }}/
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.NAME }}-${{ env.VERSION }}-service-win-x64.msi
        path: ${{ env.OUTPUT_ROOT }}/en-us/*.msi
