name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runtime: [win-x64, linux-x64, osx-x64]
    runs-on: windows-latest
    env:
      SRC: 'src'
      NAME: 'DlMirrorSync'
      FRAMEWORK: 'net8.0'
      VERSION: '0.2.0'
      OUTPUT_ROOT: 'output'
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: /DlMirrorSync
    - name: Publish-standalone
      run: dotnet publish --no-restore ./${{ env.SRC }}/${{ env.NAME }}.csproj -c Release -r ${{ matrix.RUNTIME }} --framework ${{ env.FRAMEWORK }} --self-contained true /p:Version=${{ env.VERSION }} /p:PublishReadyToRun=true /p:PublishSingleFile=True /p:PublishTrimmed=false /p:IncludeNativeLibrariesForSelfExtract=True /p:PublishDir="bin\Release/${{ env.FRAMEWORK }}/${{ env.RUNTIME }}" --output ${{ env.OUTPUT_ROOT }}/standalone/${{ matrix.RUNTIME }}
      working-directory: /DlMirrorSync
